### ISSUE TITLE
Need meta/main.yml

### ISSUE THREAD

**Issue by lukio** [gcoop-libre/ansible-lookup-plugin-pass#1]
>  [WARNING]: - gcoop.lookup-plugin-pass was NOT installed successfully: this role does not appear to have a meta/main.yml file.
> 
> ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.

**Comment by unrblt** [comment]
This isn't a role. I've updated the usage instructions, hope it's clear now.
